server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.27.0.2:3306/db_delivery?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
